apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-hog
  template:
    metadata:
      labels:
        app: cpu-hog
    spec:
      containers:
      - name: cpu-hog
        image: polinux/hello
        resources:
          requests:
            cpu: "100m"  # Requests 100m CPU
          limits:
            cpu: "1000m"  # Limits to 1000m CPU
